config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :comments, :only => [:create]
  end

  root 'home#index'

  get 'home/about', :path => "/about"
  post 'users/show', :path => "/user_info"

  devise_for :users, :path => "account"



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.blank?
      cannot :manage, :all
      basic_read_only
    elsif user.has_role?(:member)
      can :create, Topic
      can :update, Topic do |topic|
        (topic.user_id == user.id)
      end
      can :destroy, Topic do |topic|
         (topic.user_id == user.id)
      end

      can :create, Comment
      can :read, User
      basic_read_only
    else
      # banned or unknown situation
      cannot :manage, :all
      basic_read_only
    end

  end

  protected
    def basic_read_only
      can :read,Topic
      can :read, Comment
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

 belongs_to :user, dependent: :destroy
 belongs_to :topic, dependent: :destroy

 validates_presence_of :content, :user_id, :topic_id

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  belongs_to :user
  validates :user_id, presence: true
  default_scope -> { order('created_at DESC') }

  validates_presence_of :content, :title
  validates :content, presence: true

  has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_create :default_user_name

  has_many :topics, dependent: :destroy

  STATE = {
    :admin => 0,
    :normal => 1
  }

  def has_role?(role)
    case role
      when :admin then self.state == STATE[:admin]
      when :member then self.state == STATE[:normal]
      else false
    end
  end

  private

    def default_user_name
      self.name = self.email
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
	redirect_to root_path, notice: "You are not authorized to access this page."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @comment = Comment.new(comment_params)
    @comment.topic = Topic.find(params[:topic_id])
    @comment.user = current_user
    @success = @comment.save
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	puts '----------------------HomeController-----index----------------------------------'
  end

  def about
  	puts '>>>>>>>>>>>>>>>>>>>>>>>>>>>HomeController-----------about<<<<<<<<<<<<<<<<<<<<<<<<<<<<'
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    #@topics = Topic.all
    @topics = Topic.paginate(page: params[:page], :per_page => 20)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    authorize! :read, @topic
  end

  # POST /topics
  # POST /topics.json
  def create
    #@topic = Topic.new(topic_params)
    @topic = current_user.topics.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :title, :content, :hits, :like)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource only: :show

  def show
  	@user = current_user
  	@topics = current_user.topics.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
	base_title = "SimpleBlog"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=143"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def gravatar_for_header(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}/?s=23"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def find_username_by_id(user_id)
    return User.find(user_id).name
  end

end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <strong><i>
      &emsp;Posted <%= time_ago_in_words(comment.created_at) %> ago, by <%= find_username_by_id(comment.user_id)  %>
    </i></strong>
    <br/>
    &emsp;<%= comment.content %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%= escape_javascript(render :partial => @comment) %>');
$('#comment_content').val('')

app/views/home/about.html.erb
<% provide(:title, 'About') %>

<center>
  <h1>SimpleBlog</h1>
  <p>Here is <strong>SimpleBlog</strong></p>
  <p>sorry! developing..........</p>
  <p>ABOUT</p>
  <hr/>
  <h3>Hello,I'm zhangsm, the developer of simple......</h3>
</center>

app/views/home/index.html.erb
<% provide(:title, 'Home') %>

<center>
  <h1>SimpleBlog</h1>
  <p>Here is <strong>SimpleBlog</strong></p>
  <p>sorry! developing..........</p>
  <%= link_to "Topic", topics_path %>
</center>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" >
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse collapse">
        <ul class="nav" style="margin-top:8px;"><a href="/"><strong ><font size="6" color="#08c" >SimpleBlog</font></strong></a></ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <form class="navbar-search">
            <input type="text" class="search-query" placeholder="Search">
          </form>
          <li class="light-blue">
            <% if user_signed_in? %>
              <a data-toggle="dropdown" href="#" class="dropdown-toggle"> 
                <%= gravatar_for_header current_user %>
                <span class="user-info"> <small>Welcome，</small><%= current_user.name %> </span>
                <i class="icon-caret-down"></i> 
              </a>
              <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li><%= link_to "Info", users_show_path, method: "post" %> </li>
                <!-- <li> <a href="#"> <i class="icon-user"></i> 设置 </a> </li> -->
                <li><%= link_to "Account settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              </ul>
            <% else %>
              <!-- <li><a data-toggle="modal" href="#regModal" >请登陆?</a></li> -->
              <li><%= link_to "Sign in", user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </li>
        </ul> 
      </div>
    </div>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

  <%= render :partial => 'layouts/header' %>

  <div class="container">
    <div style="margin-top:15px;">
      <%if notice -%>
        <p class="alert"><%= notice %></p>
      <% end -%>
      <%if alert -%>
        <p class="alert"><%= alert %></p>
      <% end -%>
    </div>
    <div id="main" class="container-fluid">
      <%= yield %>
      <hr/>
      <footer class="footer">
        <p class="pull-right"><a href="#">返回页首</a></p>
        <p>&copy; 2014 广东工业大学 - 2011信管4 - 张水木  &nbsp; &middot; <%= link_to "SimpleBlog", root_path %> &nbsp; &middot; <%= link_to "About", home_about_path %></p>
      </footer>
    </div>
  </div>

  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for @topic, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'span5', :placeholder => 'your title......' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area topic_editor', :placeholder => 'content......' %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  topics_path, :class => 'btn' %>
    </div>
  <% end -%>
<% end %>

app/views/topics/edit.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<% provide(:title, 'Topics') %>

<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:hits) %></th>
      <th><%= model_class.human_attribute_name(:like) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.id, topic_path(topic) %></td>
        <td><%= topic.user_id %></td>
        <td><%= topic.title.to_s[0..50] %></td>
        <td><%= topic.content.to_s[0..50] %></td>
        <td><%= topic.hits %></td>
        <td><%= topic.like %></td>
        <td><%=l topic.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @topics %>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @topics, :container => false %>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_path,
            :class => 'btn btn-primary' %>
 <% end -%>

app/views/topics/new.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<% provide(:title, @topic.title.to_s[0..8]) %>

<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @topic.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @topic.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @topic.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hits) %>:</strong></dt>
  <dd><%= @topic.hits %></dd>
  <dt><strong><%= model_class.human_attribute_name(:like) %>:</strong></dt>
  <dd><%= @topic.like %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              topics_path, :class => 'btn'  %>
  <% if user_signed_in? && current_user == @topic.user -%>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_topic_path(@topic), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              topic_path(@topic),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end -%>
</div>

<div class="breadcrumb">
  <h2>About Comments</h2>
  <div id="comments">
    <%= render :partial => @topic.comments %>
  </div>
</div>

<% if user_signed_in? -%>
  <div class="form-actions">
    <%= form_for [@topic, Comment.new], :remote => true do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>
      <div class="control-group">
        <%= f.label :content, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :content, :class => 'comment_editor text_area' %>
        </div>
      </div>
      <%= f.submit 'Add comment', :class => 'btn btn-primary btn-small' %>
    <% end %>
  </div>
<% end -%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<%- model_class = User -%>
<div class="page-header">
  <div class="row">
    <div class="span2">
  	  <%= gravatar_for @user %>
    </div>
    <div class="span9" style="margin-left:-4em;">
   	  <dl class="dl-horizontal" style="margin-top:1px;">
	    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
	    <dd><%= @user.name %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
	    <dd><%= @user.email %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
	    <dd><%= @user.sign_in_count %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
	    <dd><%= @user.current_sign_in_at %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
	    <dd><%= @user.current_sign_in_ip %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
	    <dd><%= @user.last_sign_in_at %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
	    <dd><%= @user.last_sign_in_ip %></dd>
      </dl>
    </div>
  </div>
</div>

<% if @user.topics.any? %>
  <h3>Topics (<%= @user.topics.count %>)</h3>
  <table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:title) %></th>
	      <th><%= model_class.human_attribute_name(:content) %></th>
	      <th><%= model_class.human_attribute_name(:hits) %></th>
	      <th><%= model_class.human_attribute_name(:like) %></th>
	      <th><%= model_class.human_attribute_name(:created_at) %></th>
	      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @topics.each do |topic| %>
	      <tr>
	        <td><%= topic.title.to_s[0..50] %></td>
	        <td><%= topic.content.to_s[0..50] %></td>
	        <td><%= topic.hits %></td>
	        <td><%= topic.like %></td>
	        <td><%=l topic.created_at %></td>
	        <td>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_topic_path(topic), :class => 'btn btn-mini' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      topic_path(topic),
	                      :method => :delete,
	                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
<% end %>
<div class="flickr_pagination">
  <%= will_paginate @topics, :container => false %>
</div>